---
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
urlcolor: blue
# output: 
#   rmdformats::downcute:
#     self_contained: true
#     thumbnails: true
#     lightbox: true
#     gallery: false
#     highlight: tango
---
```{r setOptions, echo=FALSE}
knitr::opts_chunk$set(
  echo = FALSE, 
  fig.width = 6,
  warning = FALSE,
  message = FALSE
)
```


```{r}
library(rmdformats)
```



## Traffic Incidents in the Last 90 Minutes

<br>

The below map shows the accidents that have been reported in the last 90 minutes. Depending on the severity of the incident, it is possible that the situation has been resolved by the time you travel to the area.

```{r}
library(lubridate)
last_update <- Sys.time()
last_update <- format(last_update, tz = "Canada/Mountain", usetz = TRUE)
```

#### Information is updated every 15 minutes. 

<br>

**Last updated at `r last_update`.**

<br><br>



```{r}
# `r now(tzone = "Canada/Mountain")`.**
library(httr2)
library(leaflet)
library(dplyr)
library(lubridate)
library(janitor)
library(fontawesome)

time_frame_min <- 720
current_date_time <- Sys.time()
beginning_time <- current_date_time - lubridate::minutes(time_frame_min)

httr2::req_perform(
        request("https://data.calgary.ca/resource/35ra-9556.csv?$limit=10000000"),
        path = "00_data/yyc_traffic_incidents.csv"
        )

file_path <- "00_data/yyc_traffic_incidents.csv"

raw_traffic_incidents <- readr::read_csv(file_path)

#Data processing
traffic_incidents <- raw_traffic_incidents |>
    janitor::clean_names() |>
    mutate(
    start_dt = ymd_hms(start_dt,tz = "Canada/Mountain"),
    content = paste(description,incident_info, sep = "<br/>"),
    last_updated = ymd_hms(Sys.time(),tz = "Canada/Mountain")
        ) |>
    filter(start_dt >= beginning_time)

# glimpse(traffic_incidents)

icons <- awesomeIconList(
  walk = makeAwesomeIcon(text = fa("car-burst"), iconColor = "black", markerColor = "red")
)


```


<center>

```{r, fig.align="center", fig.width=10, fig.cap="License: Contains information licensed under the Open Government Licence – City of Calgary."}
leaflet(traffic_incidents) |>
 addTiles() |>
    addAwesomeMarkers(~longitude, ~latitude, popup = ~content,icon=icons)
```



</center>



<br>

<hr />
<p style="text-align: center;">Created by <a href="https://selica.ca">Selica Analytics</a></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://www.linkedin.com/company/selica-analytics/" class="fa fa-linkedin"></a>
</p>

&nbsp;